# Generated by Django 4.0.4 on 2023-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
