# Generated by Django 4.1.6 on 2023-02-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20230220_2209"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="citizenship_id_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="citizenship_image",
            field=models.URLField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="inactive", max_length=10),
        ),
    ]
