# Generated by Django 4.1.6 on 2023-02-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_phone_number"),
    ]

    operations = []
