# Generated by Django 4.1.6 on 2023-02-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20230221_1018"),
    ]

    operations = []
