# Generated by Django 4.1.6 on 2023-02-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20230221_1130"),
    ]

    operations = []
