# Generated by Django 4.1.6 on 2023-02-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20230221_1157"),
    ]

    operations = []
