# Generated by Django 4.1.6 on 2023-02-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20230225_2258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="citizenship_image",
            field=models.ImageField(blank=True, null=True, upload_to="citizenship/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
